<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Saal Application Test Automation Suit" duration-ms="66925" started-at="2019-05-19T10:06:57Z" finished-at="2019-05-19T10:08:04Z">
    <groups>
    </groups>
    <test name="Saal Application Test cases" duration-ms="66925" started-at="2019-05-19T10:06:57Z" finished-at="2019-05-19T10:08:04Z">
      <class name="com.saal.testcases.HomePageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.saal.testcases.HomePageTest@548e7350]" name="setUp" is-config="true" duration-ms="17683" started-at="2019-05-19T10:07:45Z" finished-at="2019-05-19T10:08:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verifyHomePageTitleTest()[pri:1, instance:com.saal.testcases.HomePageTest@548e7350]" name="verifyHomePageTitleTest" duration-ms="8" started-at="2019-05-19T10:08:03Z" finished-at="2019-05-19T10:08:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Home page title not matched expected [Dresses - My Store] but found [My account - My Store]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Home page title not matched expected [Dresses - My Store] but found [My account - My Store]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.saal.testcases.HomePageTest.verifyHomePageTitleTest(HomePageTest.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHomePageTitleTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.saal.testcases.HomePageTest@548e7350]" name="tearDown" is-config="true" duration-ms="674" started-at="2019-05-19T10:08:03Z" finished-at="2019-05-19T10:08:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.saal.testcases.HomePageTest -->
      <class name="com.saal.testcases.WomenPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.saal.testcases.WomenPageTest@1a968a59]" name="setUp" is-config="true" duration-ms="26386" started-at="2019-05-19T10:06:57Z" finished-at="2019-05-19T10:07:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="checkCatagoriesByidcheckBox()[pri:0, instance:com.saal.testcases.WomenPageTest@1a968a59]" name="checkCatagoriesByidcheckBox" duration-ms="6" started-at="2019-05-19T10:07:23Z" finished-at="2019-05-19T10:07:23Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.saal.testcases.WomenPageTest.checkCatagoriesByidcheckBox(WomenPageTest.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkCatagoriesByidcheckBox -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.saal.testcases.WomenPageTest@1a968a59]" name="tearDown" is-config="true" duration-ms="766" started-at="2019-05-19T10:07:23Z" finished-at="2019-05-19T10:07:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.saal.testcases.WomenPageTest -->
      <class name="com.saal.testcases.LoginPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.saal.testcases.LoginPageTest@5442a311]" name="setUp" is-config="true" duration-ms="20674" started-at="2019-05-19T10:07:24Z" finished-at="2019-05-19T10:07:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="loginpageTitleTest()[pri:1, instance:com.saal.testcases.LoginPageTest@5442a311]" name="loginpageTitleTest" duration-ms="1" started-at="2019-05-19T10:07:45Z" finished-at="2019-05-19T10:07:45Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.saal.testcases.LoginPageTest.loginpageTitleTest(LoginPageTest.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginpageTitleTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.saal.testcases.LoginPageTest@5442a311]" name="tearDown" is-config="true" duration-ms="686" started-at="2019-05-19T10:07:45Z" finished-at="2019-05-19T10:07:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.saal.testcases.LoginPageTest -->
    </test> <!-- Saal Application Test cases -->
  </suite> <!-- Saal Application Test Automation Suit -->
</testng-results>
